modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "flora_fantasy"
version = "${version}"
displayName = "Flora Fantasy"
authors = "ENC_Euphony"
description = '''
Look for more fantasy plants in the world!
'''
#logoFile = ""

[[dependencies.flora_fantasy]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.flora_fantasy]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.flora_fantasy]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "flora_fantasy.mixins.json"
